logging:
  level:
    org.springframework.security: INFO

spring:
  application:
    name: foodstuff
  jpa:
    database: postgresql
  datasource:
    url: jdbc:postgresql://${POSTGRES_SVC}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    # the current backend is configured to be used as a resource server
    # then, I must indicate the URI of the backend-auth to be used and which token to be used
  security:
    oauth2:
      resourceserver:
        jwt:
          # issuer-uri: ${keycloack.baseurl}/realms/my_realm
          jwk-set-uri: ${keycloak.baseurl}/realms/my_realm/protocol/openid-connect/certs
  kafka:
    consumer:
      group-id: "foodstuff-service"
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    bootstrap-servers: orbilnot-kafka:9092
server:
  port: 8000
  servlet:
    context-path: /foodstuff

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles:
        "[http.server.requests]": 0.5, 0.95, 0.99
      percentiles-histogram:
        "[http.server.requests]": true

reservation:
  events:
    topic: reservation.events
  status:
    events:
      topic: reservation.status.events
kitchen:
  status:
    events:
      topic: kitchen.status.events
product:
  update:
    status:
      events:
        topic: product.update.status.events
payment:
  status:
    events:
      topic: payment.status.events


keycloak:
  baseurl: http://keycloak/auth

user:
  account:
    url: ${keycloak.baseurl}/realms/my_realm/account/
