{
 "title": "Orbilnot Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Kitchen", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (uri)(histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{ status!~\"5..\", job=\"orbilnot-kitchen\"}[1m])) by (le)))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (uri) (histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{ status!~\"5..\", uri=~\"/user.*\"}[1m])) by (le)))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (uri) (histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{ status!~\"5..\", uri=~\"/user.*\"}[1m])) by (le)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{job=\"orbilnot-kitchen\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{status=~\"[4|5]..\", job=\"orbilnot-kitchen\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Foodstuff",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "sum by (uri)(histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{ status!~\"5..\", job=\"orbilnot-foodstuff\"}[1m])) by (le)))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (uri) (histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{ status!~\"5..\", uri=~\"/user.*\"}[1m])) by (le)))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (uri) (histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{ status!~\"5..\", uri=~\"/user.*\"}[1m])) by (le)))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_count{job=\"orbilnot-foodstuff\"}[30s])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": " Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_count{status=~\"[4|5]..\", job=\"orbilnot-foodstuff\"}[30s])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Billing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by (uri)(histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{ status!~\"5..\", job=\"orbilnot-billing\"}[1m])) by (le)))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (uri) (histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{ status!~\"5..\", uri=~\"/user.*\"}[1m])) by (le)))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (uri) (histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{ status!~\"5..\", uri=~\"/user.*\"}[1m])) by (le)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{job=\"orbilnot-billing\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{status=~\"[4|5]..\", job=\"orbilnot-billing\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Orders",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    { "title": " Error Rate", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 } },
    { "title": "RPS", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 } },
    { "title": "latency", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 } }
   ]
  }
 ]
}