apiVersion: v1
kind: Service
metadata:
  name: {{include "orbilnot.gateway.name" . }}
  labels:
    {{- include "orbilnot.labels" . | nindent 4 }}
    tier: gateway
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.gateway.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "orbilnot.selectorLabels" . | nindent 4 }}
    tier: gateway