apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{- include "orbilnot.kitchen.name" . | nindent 4}}
  labels:
    {{- include "orbilnot.labels" . | nindent 4 }}
    tier: kitchen
spec:
  replicas: {{ .Values.kitchen.replicaCount }}
  selector:
    matchLabels:
      {{- include "orbilnot.labels" . | nindent 6 }}
      tier: kitchen
  template:
    metadata:
      labels:
        {{- include "orbilnot.labels" . | nindent 8 }}
        tier: kitchen
    spec:
      serviceAccountName:
        {{- include "orbilnot.serviceAccountName" . | nindent 8}}
      initContainers:
        - name: "{{ .Chart.Name}}-init"
          image: "groundnuty/k8s-wait-for:1.3"
          imagePullPolicy: {{ .Values.kitchen.container.pullPolicy }}
          args:
            - "job"
            - "{{ .Values.job.name }}"
      containers:
        - name: {{ .Values.kitchen.name }}
          image: "{{ .Values.kitchen.container.repository}}:{{ .Values.kitchen.container.tag}}"
          imagePullPolicy: {{ .Values.kitchen.container.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Values.postgresql.configmap.name }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-creds-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-creds-secret
                  key: password
          livenessProbe:
            {{- toYaml .Values.kitchen.livenessProbe | nindent 12 }}

