apiVersion: v1
kind: Service
metadata:
  name: {{include "orbilnot.notification.name" . }}
  labels:
    {{- include "orbilnot.labels" . | nindent 4 }}
    tier: notification
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "orbilnot.selectorLabels" . | nindent 4 }}
    tier: notification