apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orbilnot
  namespace: default
subjects:
  - kind: ServiceAccount
    name: orbilnot
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: orbilnot