scrape_configs:
  - job_name: 'orbilnot-billing'
    metrics_path: '/account/actuator/prometheus'
    scrape_interval: 15s # This can be adjusted based on our needs
    static_configs:
      - targets: ['account:80']
  - job_name: 'orbilnot-order'
    metrics_path: '/order/actuator/prometheus'
    scrape_interval: 15s # This can be adjusted based on our needs
    static_configs:
      - targets: [ 'order:80' ]
  - job_name: 'orbilnot-foodstuff'
    metrics_path: '/foodstuff/actuator/prometheus'
    scrape_interval: 15s # This can be adjusted based on our needs
    static_configs:
      - targets: [ 'foodstuff:80' ]
  - job_name: 'orbilnot-kitchen'
    metrics_path: '/kitchen/actuator/prometheus'
    scrape_interval: 15s # This can be adjusted based on our needs
    static_configs:
      - targets: [ 'kitchen:80' ]
  - job_name: 'nginx'
    metrics_path: '/metrics'
    scrape_interval: 15s # This can be adjusted based on our needs
    static_configs:
      - targets: ['nginx-ingress-nginx-controller-metrics:10254']