{
 "title": "Simple Crud Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Simple Crud App Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{status=~\"[4|5]..\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(nginx_ingress_controller_request_duration_seconds_count{path=\"/simple-crud\",status=~\"5..\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{uri=~\"^/user.*\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(nginx_ingress_controller_request_duration_seconds_count{path=\"/simple-crud\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "crud-latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (uri)(histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{ status!~\"5..\", uri=~\"/user.*\"}[1m])) by (le)))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (uri) (histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{ status!~\"5..\", uri=~\"/user.*\"}[1m])) by (le)))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (uri) (histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{ status!~\"5..\", uri=~\"/user.*\"}[1m])) by (le)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{path=\"/simple-crud\", status=~\"2..\"}[1m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{path=\"/simple-crud\", status=~\"2..\"}[1m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{path=\"/simple-crud\", status=~\"2..\"}[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}