
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: qwerty
  kafka:
    bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
server:
  port: 8084

mail:
  password: dQCusbEQxLTcysPrAWWV
  username: tube90@mail.ru

keycloak:
  baseurl: http://localhost:8888/auth