logging:
  level:
    org.springframework.security: INFO
spring:
  application:
    name: notifications
  jpa:
    database: postgresql
  datasource:
    url: jdbc:postgresql://${POSTGRES_SVC}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  kafka:
    consumer:
      group-id: "notification-service"
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            type:
              mapping: paymentEvent:com.gegunov.model.PaymentEvent
    bootstrap-servers: orbilnot-kafka:9092
openapi:
  orbilnot:
    base-path: /
server:
  port: 8000
  servlet:
    context-path: /notifications

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles:
        "[http.server.requests]": 0.5, 0.95, 0.99
      percentiles-histogram:
        "[http.server.requests]": true

payment:
  events:
    topic: payment.event
order:
  events:
    topic: order.event