spring:
  jpa:
    database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5431/postgres
    username: postgres
    password: qwerty
  kafka:
    bootstrap-servers: localhost:9092


keycloak:
  baseurl: http://localhost:8888/auth
server:
  port: 8084
